### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JamiKettunen** [sailfishos-oneplus5/boot-switcher#1]
- [x] Implement [AnyKernel3](https://github.com/osm0sis/AnyKernel3) by @osm0sis to reduce zip size further & make flashing process faster
- [x] Start using SFOS' `/boot/hybris-boot.img` instead of the one backed up to `/data/.stowaways/hybris-boot.img` for simpler OTAs & space savings
- [x] Figure out a way to do OTA while updating `/data/.stowaways/hybris-boot.img` as well
- [ ] Make sure indentation is not lost due to [unmounted `/system`](https://github.com/sailfishos-oneplus5/boot-switcher/blob/22da9f88e764aa9bdf5b8c3a54c47cf0d083b0ef/boot-switcher/META-INF/com/google/android/update-binary#L75) when [`wc` binary is called](https://github.com/sailfishos-oneplus5/boot-switcher/blob/22da9f88e764aa9bdf5b8c3a54c47cf0d083b0ef/boot-switcher/META-INF/com/google/android/update-binary#L112) (this doesn't make much sense!)
